### ISSUE TITLE
PhoneAuthProvider support

### ISSUE THREAD

**Issue by lex-shvets** [RxSwiftCommunity/RxFirebase#14]
Would be nice with support for phone number authentification.

**Comment by arnauddorgans** [comment]
What do you need ? 
```PhoneAuthProvider.provider().verifyPhoneNumber``` ?

**Comment by arnauddorgans** [comment]
@ShvetsJr tell me if you need something else, otherwise i'll merge #15

**Comment by lex-shvets** [comment]
Yes, cool! Thanks!

Would be nice to have Auth.auth().signInAndRetrieveData(with: credential) as well :) 

`let credential = PhoneAuthProvider.provider().credential(withVerificationID: verificationID.value, verificationCode: code.value)
        Auth.auth().signInAndRetrieveData(with: credential)`

**Comment by arnauddorgans** [comment]
You already have it with:

```Auth.auth().rx.signInAndRetrieveData(with: crediential)```

**Comment by lex-shvets** [comment]
Awesome! Sorry, didn't see it. I will close the issues now 👍

**Comment by lex-shvets** [comment]
I did update pods but I could not see any changes even tho I see it in develop :( @arnauddorgans

**Comment by arnauddorgans** [comment]
Sorry dude I totally forgot to push the release, you can update right now @ShvetsJr
