### ISSUE TITLE
getDocument with source

### ISSUE THREAD

**Issue by lex-shvets** [RxSwiftCommunity/RxFirebase#16]
Would be nice to get an option to select where to get data from. Server or cache, like following:
<img width="710" alt="Screenshot 2019-03-31 at 16 47 50" src="https://user-images.githubusercontent.com/26301411/55290573-15c6cb80-53d5-11e9-9edd-e1252be9b9da.png">

**Comment by arnauddorgans** [comment]
Anything else ? :) #17

**Comment by lex-shvets** [comment]
Nothing special that I have on my mind right now. Will let you know if I come up with something 😁😛 Thanks for such amazing library and for so quick responses! My project lives on it 🙂

**Comment by arnauddorgans** [comment]
My pleasure 😃 
Available in 0.3.6 👍
