### ISSUE TITLE
How about using `Single` instead of `Observable`?

### ISSUE THREAD

**Issue by geonu1109** [RxSwiftCommunity/RxFirebase#18]
In the `RxFirebase/Sources/Database/FIRDatabaseQuery+Rx.swift` file, the `observeSingleEvent` method returns only one result value, but the return type is `Observable` instead of `Single`. I suggest changing this to `Single`.

**Comment by arnauddorgans** [comment]
You are right 👍 i'll work on it on the next release

**Comment by success-0627** [comment]
thank you @acecilia 
you solved this issue too on v0.3.8!
