### ISSUE TITLE
RxSwift Firestore extension is not working

### ISSUE THREAD

**Issue by Jigneshmayani90** [RxSwiftCommunity/RxFirebase#24]
Here is my Original code that is working i am getting data from firestore 

        db.collection(UserNode).document("affdToWcXulhFtlFdcqm").collection(MessageNode).whereField("isDelete", isEqualTo:false)
            .addSnapshotListener
            { querySnapshot, error in

                guard let snapshot = querySnapshot else
                {
                    return
                }

                snapshot.documentChanges.forEach { diff in

                    if (diff.type == .added)
                    {
                   // Here I am getting Data
                    }
                    if (diff.type == .modified)
                    {
                        print("Modified : \(diff.document.data())")
                    }
                    if (diff.type == .removed)
                    {
                        print("Removed : \(diff.document.data())")
                    }
                }
        }

Same Thing i want to do with Rxfirebase with this code

        db.collection(UserNode).document("affdToWcXulhFtlFdcqm").collection(MessageNode).whereField("isDelete", isEqualTo:false).rx.listen()
            .subscribe(onNext: { snapshot in
                snapshot.documentChanges.forEach { diff in
                    if (diff.type == .added) {
                        print("Added: \(diff.document.data())")
                    }
                    if (diff.type == .modified) {
                        print("Modified: \(diff.document.data())")
                    }
                    if (diff.type == .removed) {
                        print("Removed: \(diff.document.data())")
                    }
                }
            }, onError: { error in
                print("Error fetching snapshots: \(error)")
            }).disposed(by: disposeBag)

But in my case i am not getting Data event from firestore

But I am able to save data on firestore with Rxswift by using this method 

        docRef.rx.updateData([stringKey:true]).subscribe(onNext:
        { _ in
            // Success
        }).disposed(by: disposeBag)

Please help me i am doing any mistake ? I can update data. but  i am not able to retrieve data.

**Comment by arnauddorgans** [comment]
Hi, sorry i'm late

I did some tests with your code and i'm able to get data event from firestore.

<img width="1256" alt="Capture d’écran 2019-07-10 à 10 45 43" src="https://user-images.githubusercontent.com/10015557/60954803-e42c9d00-a2ff-11e9-85bf-b57a5d97a7e8.png">

<img width="476" alt="Capture d’écran 2019-07-10 à 10 41 35" src="https://user-images.githubusercontent.com/10015557/60954753-d1b26380-a2ff-11e9-899f-69f4c1b86f71.png">

<img width="529" alt="Capture d’écran 2019-07-10 à 10 46 13" src="https://user-images.githubusercontent.com/10015557/60954840-f6a6d680-a2ff-11e9-8f0f-76a66aeb70d7.png">

Can you add a `.debug()` just before your subscribe ? Maybe your subscription is disposed before getting any event for some reasons.

**Comment by Jigneshmayani90** [comment]
Arnauddorgans i just removed disposed(by: disposeBag) and i am getting event you are right.

Thanks for your Help.
