### ISSUE TITLE
Firebase dependencies are outdated.

### ISSUE THREAD

**Issue by success-0627** [RxSwiftCommunity/RxFirebase#28]
[!] CocoaPods could not find compatible versions for pod "FirebaseDatabase":
  In Podfile:
    Firebase/Database was resolved to 6.6.0, which depends on
      FirebaseDatabase (~> 6.0.0)

    RxFirebase/Database (from `https://github.com/RxSwiftCommunity/RxFirebase`, commit `7fa6cf69e79af485858509fc93103aad1348fa69`) was resolved to 0.3.7, which depends on
      RxFirebaseDatabase (~> 0.3) was resolved to 0.3.7, which depends on
        FirebaseDatabase (~> 5)

**Comment by success-0627** [comment]
I think this [PR](https://github.com/RxSwiftCommunity/RxFirebase/pull/27#issue-319224398) is solution and when would you like to merge ?

**Comment by success-0627** [comment]
[!] CocoaPods could not find compatible versions for pod "FirebaseCore":
  In Podfile:
    RxFirebase/Database (from `https://github.com/RxSwiftCommunity/RxFirebase.git`, branch `develop`) was resolved to 0.3.8, which depends on
      RxFirebaseDatabase (~> 0.3) was resolved to 0.3.7, which depends on
        FirebaseDatabase (~> 5) was resolved to 5.1.1, which depends on
          FirebaseCore (~> 5.2)

**Comment by success-0627** [comment]
Please check this.
https://github.com/firebase/FirebaseUI-iOS/issues/722
This library needs to be updated, otherwise how could we keep using this library with outdated dependencies?

**Comment by arnauddorgans** [comment]
I working on it, 0.3.8 will be available soon :)

**Comment by arnauddorgans** [comment]
Available :)

**Comment by success-0627** [comment]
You are my hero

**Comment by arnauddorgans** [comment]
Sorry for the delay guys
